---
# Follow official documentation - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_rhel_8_for_sap_hana_2_installation/

- hosts: hanas

  vars:
    sap_preconfigure_fail_if_reboot_required: no
    sap_hana_preconfigure_fail_if_reboot_required: no
    sap_hana_preconfigure_update: yes
    
  roles:
    - role: sap-preconfigure
    - role: sap-hana-preconfigure
